// File Name:	EDeviceStatusNo.h
// Description:	Device Status No.
// Engineer:	Taro Fuji
// Last Edit:	2015/03/17
// Revision:	XX
//
// Copyright (C) by Fuji Xerox Advanced Technology Co.,Ltd. All rights reserved.
//

#ifndef EDeviceStatusNo_h
#define EDeviceStatusNo_h
typedef enum /*EDeviceStatusNo*/
{
	DSNO_DOWNLOAD_MODE_FAIL,	//0
	DSNO_STATIC_JAM,
	DSNO_CMPL_EXIT_SNR_ON_JAM,
	DSNO_CMPL_EXIT_SNR_OFF_JAM,
	DSNO_SET_EJECT_JAM,
	DSNO_NVM_FAIL,
	DSNO_RIGHT_TAMPER_ON_FAIL,
	DSNO_RIGHT_TAMPER_OFF_FAIL,
	DSNO_LEFT_TAMPER_ON_FAIL,
	DSNO_LEFT_TAMPER_OFF_FAIL,
	
	DSNO_STAPLE_FAIL,				//10
	DSNO_EJECT_BELT_HOME_ON_FAIL,
	DSNO_EJECT_BELT_HOME_OFF_FAIL,
	DSNO_SETCLAMP_HOME_ON_FAIL,
	DSNO_SETCLAMP_HOME_OFF_FAIL,
	DSNO_PADDLE_HOME_ON_FAIL,
	DSNO_PADDLE_HOME_OFF_FAIL,
	DSNO_STACKER_TRAY_FAIL,
	DSNO_STACKER_UPLIMIT_FAIL,
	DSNO_STACKER_LOWLIMIT_FAIL,
	
	DSNO_STAPLE_COVER_24V_FAIL,	//20
	DSNO_REAR_COVER_ILK_OPEN,
	DSNO_STAPLE_COVER_ILK_OPEN,
	DSNO_INIT_STATE,				
	DSNO_STAPLE_READY_FAIL,		
	DSNO_STAPLE_SUPPLY_LEVEL,
	DSNO_STACKER_FULL_STACK,
	DSNO_STACKER_LOW_SAFETY,
	DSNO_STAPLE_STATUS_NG,
	DSNO_SCARCH_SHEET_COMPILE,
	
	DSNO_SYS_CONT_COMM_FAIL,
	DSNO_LOGIC_FAIL,	
	
	DSNO_NUM,
}EDeviceStatusNo;
/*
typedef enum // EDeviceStatusNo
{
	DSNO_DOWNLOAD_MODE_FAIL			= 0,
	DSNO_LOGIC_FAIL                 = 1,
	DSNO_SYS_CONT_COMM_FAIL         = 2,
	DSNO_STATIC_JAM                 = 3,
	DSNO_ENT_SNR_ON_JAM             = 4,
	DSNO_CMPL_EXIT_SNR_ON_JAM       = 5,
	DSNO_CMPL_EXIT_SNR_OFF_JAM      = 6,
	DSNO_SET_EJECT_JAM              = 7,
	DSNO_SPEC_OUT_JAM               = 8,

	DSNO_LEFT_TAMPER_ON_FAIL  	   = 9,
	DSNO_LEFT_TAMPER_OFF_FAIL  	   = 10,
	DSNO_RIGHT_TAMPER_ON_FAIL      = 11,
	DSNO_RIGHT_TAMPER_OFF_FAIL     = 12,
	DSNO_EJECT_HOME_ON_FAIL   	   = 13,
	DSNO_EJECT_HOME_OFF_FAIL  	   = 14,

	DSNO_STAPLE_FAIL               = 15,
	DSNO_COVER_OPEN                = 16,
	DSNO_INIT_STATE                = 17,
	DSNO_STAPLE_SUPPLY_LEVEL       = 18,
	DSNO_STAPLE_READY_FAIL         = 19,
	DSNO_OUT_TRAY_FULL_STACK       = 20,
	DSNO_STAPLE_NG                 = 21,
	DSNO_NVM_FAIL				   = 22,

	DSNO_PADDLE_HOME_ON_FAIL       = 23,
	DSNO_PADDLE_HOME_OFF_FAIL      = 24,
	DSNO_SETCLAMP_HOME_ON_FAIL     = 25,
	DSNO_SETCLAMP_HOME_OFF_FAIL    = 26,

	DSNO_NUM                       = 27,
}EDeviceStatusNo;
*/

#endif          // EDeviceStatusNo_h
